### ISSUE TITLE
[Sugerencia] Agregar opción de páginas

### ISSUE THREAD

**Issue by PanBimboBoy** [Ajneb97/Codex#18]
Esta opción de páginas se podía "falsear" antes del rework de Codex creando varias "sub-categorias" en inventory.yml, pero ahora se necesita estar ligado una "sub-categoria" de inventory.yml por una "Codex/categorys/sub-categoría", si se reutiliza no funciona y se bugea.

Lo que me refiero que ahora debe tener el prefijo `category_[name]` para poder vincular los mobs agregados en `Codex/categorys/`  y esto hace que nos toque crear demasiados "sub-categorias" para crear páginas y no se puede utilizar en 2 o más subcategorías el listado de discoveries.

Por este motivo, sería capaz de agregar la opción de páginas sería tipo así, lo cual nos ayudaría bastante en esta update
```yaml

    23: # SPAWN
      page: 2
      item:
        id: PAPER
        name: '&7&lLocalización'
```

Video demostrativo de como se mostraba antes del rework:

https://github.com/user-attachments/assets/7f5bc2d0-eb0e-4924-8263-afc7bf779080
