### ISSUE TITLE
MYTHIC_MOB_KILL discovery type also triggers MOB_KILL

### ISSUE THREAD

**Issue by KermX** [Ajneb97/Codex#20]
If I have a MYTHIC_MOB_KILL discovery that triggers on a mythic mob based on a pig it will also trigger MOB_KILL if I have another discovery for killing a regular pig. This bug should be corrected by making sure MYTHIC_MOB_KILL does not trigger MOB_KILL for the mob it is based on.

**Comment by Ajneb97** [comment]
Can you send me both discoveries configs?

**Comment by KermX** [comment]
> Can you send me both discoveries configs?

Let me know if you would like the full files. The Mythic mob moose is based on a cow so killing it will trigger both discoveries. 
```
  moose:
    name: "#B92727&l♢ #9D2626&lM#8F2525&lo#802424&lo#722424&ls#642323&le"
    description:
      - " "
      - "&7World: Overworld"
      - "&7Biomes:"
      - "&7⇢ Taigas"
      - "&7Drops:"
      - "&7⇢ Moose Antler"
    discovered_on:
      type: MYTHIC_MOB_KILL
      value:
        mob_type: moose
```

```
  cow:
    name: "#B92727&l♢ #8F2525&lC#792424&lo#642323&lw"
    description:
      - " "
      - "&7World: Overworld"
      - "&7Biome: Any"
      - "&7Drops:"
      - "&7⇢ Raw Beef"
    discovered_on:
      type: MOB_KILL
      value:
        mob_type: COW
```
