### ISSUE TITLE
[BUG] Placeholder API

### ISSUE THREAD

**Issue by XXX10Tacles** [Ajneb97/Codex#21]
Placeholders from placeholderapi stopped working after that update [2.0.1](https://www.spigotmc.org/resources/codex-rpg-discoveries-1-16-5-1-21-5.90371/update?update=573897)

![Image](https://github.com/user-attachments/assets/007853ee-a397-49f8-a4d2-c7daee58a56b)

**Comment by XXX10Tacles** [comment]
Before update: 

![Image](https://github.com/user-attachments/assets/1c9a8982-afec-44f7-b1c3-aa9c48826558)

**Comment by Ajneb97** [comment]
Those placeholders are set on the discovery lore?

**Comment by XXX10Tacles** [comment]
> Those placeholders are set on the discovery lore?

in inventory.yml here is simplified version of that part:

```
  category_charactermenu:
    slots: 45
    title: "&8Server Info"

    3:
      item:
        id: DIAMOND_HELMET
        name: '&aInventory'
        lore:
        - ' %mmocore_stat_health_regeneration%'
```
